CREATE DATABASE IF NOT EXISTS demo;

USE demo;

DROP TABLE employee;
CREATE TABLE employee (
  id BIGINT PRIMARY KEY AUTO_INCREMENT
 ,name TEXT NOT NULL
 ,department ENUM('system', 'sales', 'general', 'others') NOT NULL
 ,create_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
 ,update_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE branch;
CREATE TABLE branch (
  id BIGINT PRIMARY KEY AUTO_INCREMENT
 ,branch_no INT NOT NULL
 ,name TEXT NOT NULL
 ,create_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
 ,update_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);